### ISSUE TITLE
Test in local with update not webhook

### ISSUE THREAD

**Issue by Katerou22** [luckydonald/teleflask#2]
**Hey there,**

How i cant test it on local not by webhook? i explore base files, i didnt find out how to test it with out webhook

**Comment by luckydonald** [comment]
There currently is no build in way. However you might get it to work with `ngrok` [(website)](https://ngrok.com/) or a similar service which proxy external requests to localhost.

I'll be working on a solution though.

**Comment by luckydonald** [comment]
There is now a proxy tool:
```
python -m teleflask.proxy "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11" localhost 8080
```


It will land with 2.0.0, but can already installed with a development pre-release like `v2.0.0.dev16` or later:
```bash
pip install -e git://github.com/luckydonald/teleflask.git@v2.0.0.dev16#egg=teleflask
```
